"""make num_of_reviews and num_of_stars  nullable

Revision ID: 7ec7888b2909
Revises: 
Create Date: 2026-06-05 23:09:21.995712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec7888b2909'
down_revision = None
branch_labels = None
depends_on = None

naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouse_model', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_unique_constraint(None, ['product_name'])

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.alter_column('num_of_stars',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('num_of_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.alter_column('num_of_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('num_of_stars',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('mouse_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
