# General Rules ids

HAND_SIZE = "USER_HAND_SIZE"
SMALL_HAND_SIZE = 115
MEDIUM_HAND_SIZE = 130

BUDGET = "BUDGET"
BUDGET_BUFFER = 0.05 # 5%

CONNECTIVITY = "CONNECTIVITY_PREFERENCE"

LEFT_HANDED = "LEFT_HAND"

USER_TYPE = "USER_TYPE"
OFFICE_WORKER = "OFFICE_WORKER"
GAMER = "GAMER"
STUDENT = "STUDENT"

# Gamer Rules

TYPE_OF_GAME = "TYPE_OF_GAME"
MINIMUM_BUTTONS_MMORPG = 10
REQUIRED_DPI_FPS = 16000
REQUIRED_TRACKING_SPEED_FPS = 400
REQUIRED_MOUSE_WEIGHT_FPS = 80

REQUIRED_DPI_RTS = 8000
REQUIRED_POLLING_RATE_RTS = 1000

REQUIRED_POLLING_RATE_MOBA = 500
REQUIRED_DPI_MOBA = 4000

LIGHT_WEIGHT_MOUSE = "LIGHT_WEIGHT"
LIGHT_WEIGHT = 80
MODERATE_WEIGHT = 100


RGB_LIGHTING = "RGB_PREFERRED"

# Student Rules

TRAVEL_PORTABILITY = "PORTABILITY"
REQUIRED_WEIGHT_PORT = 100

EXTRA_BUTTONS_REQUIRED = "EXTRA_BUTTONS_REQUIRED"
NUMBER_OF_BUTTONS = 6

# Office Rules

LONG_HOURS = "WORK_LONG_HOURS"

SHORTCUT_BUTTONS_REQUIRED = "SHORTCUT_BUTTONS_REQUIRED"

BATTERY_LIFE_IMPORTANCE = "BATTERY_LIFE_IMPORTANCE"

PROFESSIONAL_LOOK_REQUIRED = "PROFESSIONAL_LOOK_REQUIRED"

# Weights - general
DOMINANT_FACTOR = 2.5
MAJOR_FACTOR = 2.0
MODERATE_FACTOR = 1.5
NORMAL_FACTOR = 1.0
MINOR_FACTOR = 0.5

NEGATIVE_DOMINANT_FACTOR = -2.5
NEGATIVE_MAJOR_FACTOR = -2.0
NEGATIVE_MODERATE_FACTOR = -1.5
NEGATIVE_NORMAL_FACTOR = -1.0
NEGATIVE_MINOR_FACTOR = -0.5

# Weights - customs
ERGONOMY_FACTOR = 3.0
